# Generated by Django 3.0.8 on 2021-01-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210112_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referenceID',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
