# Generated by Django 3.0.8 on 2021-01-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=30)),
                ('reference', models.TextField(max_length=20)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
