# Generated by Django 3.0.8 on 2021-01-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Levels',
            new_name='Level',
        ),
    ]
